# Generated by Django 4.1.5 on 2023-01-19 05:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Game Title')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='About Game')),
                ('price', models.IntegerField(default=0)),
                ('gameimg', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created, ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created, ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created, ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=50, null=True, verbose_name='Card Number')),
                ('amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created, ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
